Repository cds-snc/report-a-cybercrime, pull requests merged in 2020-04, with the labels that each got.

#1741 App header and footer regions
  f2/src/components/footer/footer.stories.mdx
  f2/src/components/topbanner/index.js
  f2/src/components/topbanner/topbanner.stories.mdx
  f2/src/components/warning-banner/index.js
Labels: documentation

#1783 update next page text for consent page
  f2/src/locales/en.json
  f2/src/locales/fr.json
Labels: high priority

#1774 Contact info email validation not allowing valid email addresses
  f2/package-lock.json
  f2/package.json
  f2/src/forms/ContactInfoForm.js
  f2/src/forms/__tests__/ContactInfoForm.test.js
Labels: need for launch

#1782 Reformat postal code
  f2/src/LocationPage.js
  f2/src/forms/LocationInfoForm.js
  f2/src/forms/__tests__/LocationInfoForm.test.js
  f2/src/utils/__tests__/formatPostalCode.test.js
  f2/src/utils/formatPostalCode.js
Labels: medium priority

#1776 Stop server crash for anonymous reports
  f2/src/ConfirmationPage.js
Labels: need for launch

#1785 add instructions for getting unencrypted analyst email
  README.md
Labels: medium priority

#1784 remove unused optionOther field
  f2/src/ConfirmationSummary.js
  f2/src/forms/WhatWasAffectedForm.js
  f2/src/utils/formatAnalystEmail.js
Labels: medium priority

#1770 Show anonymous location on conf screen and report
  f2/src/forms/LocationAnonymousInfoForm.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
  f2/src/summary/LocationInfoSummary.js
  f2/src/utils/formatAnalystEmail.js
Labels: need for launch

#1789 Import EditButton from components on summary block pages
  f2/src/ConfirmationSummary.js
  f2/src/summary/BusinessInfoSummary.js
  f2/src/summary/ContactInfoSummary.js
  f2/src/summary/DevicesSummary.js
  f2/src/summary/EvidenceInfoSummary.js
  f2/src/summary/HowDidItStartSummary.js
  f2/src/summary/InformationSummary.js
  f2/src/summary/LocationInfoSummary.js
  f2/src/summary/MoneyLostInfoSummary.js
  f2/src/summary/SuspectCluesSummary.js
  f2/src/summary/WhatHappenedSummary.js
  f2/src/summary/WhatWasAffectedSummary.js
Labels: medium priority

#1760 check file extension better
  f2/src/forms/EvidenceInfoForm.js
Labels: high priority

#1751 Update packages
  f2/cypress/integration/homepage.feature
  f2/cypress/integration/homepage/homepage.js
  f2/cypress/videos/examples/aliasing.spec.js.mp4
  f2/package-lock.json
  f2/package.json
  f2/src/forms/__tests__/ContactInfoForm.test.js
Labels: medium priority

#1788 .env local mail var for anonymous reports
  f2/src/utils/encryptedEmail.js
Labels: medium priority

#1792 Change CAFC redirect to https
  f2/server.js
Labels: low priority

#1798 [Need for launch]Added the required GTM tag identifiers
  f2/src/ThankYouPage.js
Labels: accessibility, high priority, need for launch

#1748 add extra message for unsuccessful report
  f2/src/ThankYouPage.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
Labels: high priority

#1791 added a c19 Well component as detail summary. Added a polyfill as dep.
  f2/src/Covid19Page.js
  f2/src/Home.js
  f2/src/LandingPage.js
  f2/src/components/Page/index.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
Labels: C19, need for launch

#1817 adding gtm hotfix
  f2/azure-pipelines.yaml
Labels: HOTFIX 🔥

#1773 Sanitize html tags out of user inputs
  f2/package-lock.json
  f2/package.json
  f2/server.js
  f2/src/utils/__tests__/sanitize.test.js
  f2/src/utils/notify.js
  f2/src/utils/sanitize.js
Labels: high priority

#1768 add prodVersion to report
  f2/src/App.js
  f2/src/forms/__tests__/BusinessInfoForm.test.js
  f2/src/forms/__tests__/DevicesForm.test.js
  f2/src/forms/__tests__/FinalFeedbackForm.test.js
  f2/src/forms/__tests__/HowDidItStartForm.test.js
  f2/src/forms/__tests__/InformationForm.test.js
  f2/src/forms/__tests__/MoneyLostInfoForm.test.js
  f2/src/forms/__tests__/PrivacyConsentInfoForm.test.js
  f2/src/forms/__tests__/WhatHappenedForm.test.js
  f2/src/forms/__tests__/WhatWasAffectedForm.test.js
  f2/src/utils/formatAnalystEmail.js
  f2/src/utils/state.js
Labels: high priority

#1802 Updated business form
  f2/src/ConfirmationPage.js
  f2/src/ConfirmationSummary.js
  f2/src/forms/BusinessInfoForm.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
  f2/src/summary/BusinessInfoSummary.js
  f2/src/utils/formatAnalystEmail.js
Labels: medium priority

#1810 Refactor form default values
  f2/src/ConfirmationSummary.js
  f2/src/LocationPage.js
  f2/src/forms/AnonymousInfoForm.js
  f2/src/forms/BusinessInfoForm.js
  f2/src/forms/DevicesForm.js
  f2/src/forms/EvidenceInfoForm.js
  f2/src/forms/HowDidItStartForm.js
  f2/src/forms/InformationForm.js
  f2/src/forms/LocationAnonymousInfoForm.js
  f2/src/forms/LocationInfoForm.js
  f2/src/forms/MoneyLostInfoForm.js
  f2/src/forms/SuspectCluesForm.js
  f2/src/forms/WhatHappenedForm.js
  f2/src/forms/WhatWasAffectedForm.js
  f2/src/forms/defaultValues.js
  f2/src/utils/__tests__/areFieldsValid.test.js
  f2/src/utils/areFieldsValid.js
Labels: high priority

#1820 Anonymous flow opt-in
  f2/src/AnonymousPage.js
  f2/src/ConfirmationPage.js
  f2/src/ConfirmationSummary.js
  f2/src/LocationPage.js
  f2/src/__tests__/ConfirmationSummary.test.js
  f2/src/__tests__/LocationPage.test.js
  f2/src/forms/AnonymousInfoForm.js
  f2/src/forms/__tests__/AnonymousInfoForm.test.js
  f2/src/forms/defaultValues.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
  f2/src/utils/__tests__/formatAnalystEmail.test.js
  f2/src/utils/formatAnalystEmail.js
Labels: medium priority

#1838 number of submissions and availability not rolling over with new day
  f2/src/utils/checkIfAvailable.js
  f2/src/utils/saveRecord.js
Labels: HOTFIX 🔥, high priority

#1839 deleteFormData populates empty report with initialState
  f2/src/utils/state.js
Labels: high priority

#1848 fixing translations
  f2/src/locales/en.json
  f2/src/locales/fr.json
Labels: high priority

#1852 recognize French url
  f2/server.js
  f2/src/i18n.config.js
Labels: high priority

#1846 pull submissions hotfix into master
  f2/src/utils/checkIfAvailable.js
  f2/src/utils/saveRecord.js
Labels: high priority

#1863 Move submitted and reportId out of formData
  f2/src/ConfirmationPage.js
  f2/src/FinalFeedbackPage.js
  f2/src/ThankYouPage.js
  f2/src/components/EditButton/__tests__/EditButton.test.js
  f2/src/components/EditButton/index.js
  f2/src/forms/ConfirmationForm.js
  f2/src/forms/defaultValues.js
  f2/src/utils/state.js
Labels: high priority

#1878 Changing log from error to info
  f2/server.js
Labels: medium priority
