Repository cds-snc/report-a-cybercrime, pull requests merged in 2020-03, with the labels that each got.

#1625 new page should be opened
  f2/src/ThankYouPage.js
Labels: bug, high priority

#1629 Don't save malware!
  f2/src/utils/saveBlob.js
Labels: need for launch

#1635 Fix link to previous version
  f2/src/App.js
Labels: need for launch

#1621 Fix Banner Bug
  f2/azure-pipelines.yaml
Labels: high priority, infrastructure

#1619 Fix for Logs in another Azure Subscription
  utils/azurescript.sh
Labels: infrastructure, medium priority

#1597 Updating Azurescript - IMAGE_NAME
  utils/azurescript.sh
Labels: low priority

#1643 more detailed p and text stories
  .github/PULL_REQUEST_TEMPLATE.md
  f2/src/components/paragraph/paragraph.stories.mdx
  f2/src/components/text/text.stories.mdx
Labels: documentation

#1671 added stuff to sb docs
  f2/src/components/link/index.js
  f2/src/components/link/link.stories.mdx
  f2/src/components/list-item/list-item.stories.mdx
  f2/src/locales/en.json
  f2/src/locales/fr.json
Labels: documentation

#1661 added getting started page to storybook
  f2/.storybook/theme.js
  f2/src/__stories__/Start.stories.mdx
  f2/src/components/button/Button.stories.js
  f2/src/components/checkbox/checkbox.stories.mdx
Labels: documentation

#1664 Reports a day counter
  f2/server.js
  f2/src/utils/checkIfAvailable.js
  f2/src/utils/getData.js
  f2/src/utils/saveRecord.js
Labels: high priority

#1675 Fixed Field, added container and layout to sb
  f2/src/components/Field/Field.stories.js
  f2/src/components/Field/Field.stories.mdx
  f2/src/components/Field/index.js
  f2/src/components/container/container.stories.js
  f2/src/components/container/container.stories.mdx
  f2/src/components/layout/index.js
  f2/src/components/layout/layout.stories.mdx
Labels: documentation

#1690 Fix for Continuous Deployment
  utils/azurescript.sh
Labels: low priority

#1684 Storybook Forms wiki/howto
  f2/src/__stories__/Forms.stories.mdx
  f2/src/components/FormArrayControl/FormArrayControl.stories.mdx
  f2/src/components/FormArrayControl/index.js
Labels: documentation

#1731 Sb descriptionlist
  f2/src/__stories__/Forms.stories.mdx
  f2/src/components/DescriptionListItem/DescriptionListItem.stories.mdx
  f2/src/components/button/Button.stories.js
Labels: documentation

#1733 sb doc for Pages. Reorganized Layout and Form sections
  f2/src/__stories__/Forms.stories.mdx
  f2/src/__stories__/Pages.stories.mdx
  f2/src/components/layout/layout.stories.mdx
Labels: documentation

#1736 Summary doc
  f2/src/ConfirmationSummary.js
  f2/src/__stories__/Start.stories.mdx
  f2/src/__stories__/Summary.stories.mdx
  f2/src/components/EditButton/__tests__/EditButton.test.js
  f2/src/components/EditButton/index.js
Labels: documentation

#1744 Typos in sb documentation
  f2/src/App.js
  f2/src/__stories__/Summary.stories.mdx
Labels: documentation
