Repository cds-snc/report-a-cybercrime, pull requests merged in 2020-05, with the labels that each got.

#1865 Reports Submitted counter not initialized after reboot
  f2/server.js
  f2/src/utils/checkIfAvailable.js
  f2/src/utils/saveRecord.js
Labels: bug, high priority

#1841 New e2e Tests - Merging Hong's code
  f2/cypress/fixtures/form_data.json
  f2/cypress/fixtures/girl.jpg
  f2/cypress/fixtures/gun-picture.jpg
  f2/cypress/fixtures/rentalForm.jpg
  f2/cypress/integration/CancelAtPrivacy.feature
  f2/cypress/integration/CancelAtPrivacy/cancelAtPrivacy.js
  f2/cypress/integration/Consent/consent.js
  f2/cypress/integration/generate_full_anony_report_en.feature
  f2/cypress/integration/generate_full_anony_report_en/generate_full_anony_report_en.js
  f2/cypress/integration/generate_full_report_en.feature
  f2/cypress/integration/generate_full_report_en/generate_full_report_en.js
  f2/cypress/integration/generate_full_report_fr.feature
  f2/cypress/integration/generate_full_report_fr/generate_full_report_fr.js
  f2/cypress/integration/homepage.feature
  f2/cypress/integration/homepage/homepage.js
Labels: e2e

#1912 Cyptocurrency shows up as cash in e-mail
  f2/src/forms/MoneyLostInfoForm.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
Labels: bug

#1941 Disable FTP(S)
  utils/azurescript.sh
Labels: infrastructure
