Repository cds-snc/report-a-cybercrime, pull requests merged in 2020-02, with the labels that each got.

#1257 Ammended the script to make it runnable
  utils/azurescript.sh
Labels: infrastructure

#1259 stacked mobile buttons
  f2/src/components/button/index.js
  f2/src/components/next-and-cancel-buttons/_tests_/next-and-cancel-buttons.test.js
  f2/src/components/next-and-cancel-buttons/index.js
  f2/src/forms/__tests__/BusinessInfoForm.test.js
  f2/src/forms/__tests__/ContactInfoForm.test.js
  f2/src/forms/__tests__/DevicesForm.test.js
  f2/src/forms/__tests__/InformationForm.test.js
  f2/src/forms/__tests__/LocationInfoForm.test.js
  f2/src/forms/__tests__/MoneyLostInfoForm.test.js
  f2/src/forms/__tests__/PrivacyConsentInfoForm.test.js
  f2/src/forms/__tests__/WhatHappenedForm.test.js
  f2/src/forms/__tests__/WhatWasAffectedForm.test.js
Labels: frontend

#1274 Adding OpenSSL to Dockerfile
  f2/Dockerfile
Labels: need for launch

#1273 Information summary display for other
  f2/src/ConfirmationSummary.js
  f2/src/forms/InformationForm.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
  f2/src/summary/InformationSummary.js
Labels: need for launch

#1276 formatList util
  f2/package-lock.json
  f2/package.json
  f2/src/App.js
  f2/src/ConfirmationPage.js
  f2/src/ConfirmationSummary.js
  f2/src/__tests__/ConfirmationSummary.test.js
  f2/src/components/phase-banner/index.js
  f2/src/forms/InformationForm.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
  f2/src/summary/HowDidItStartSummary.js
  f2/src/summary/InformationSummary.js
  f2/src/summary/MoneyLostInfoSummary.js
  f2/src/summary/WhatWasAffectedSummary.js
  f2/src/summary/__tests__/BusinessInfoSummary.test.js
  f2/src/summary/__tests__/DevicesSummary.test.js
  f2/src/summary/__tests__/HowDidItStartSummary.test.js
  f2/src/summary/__tests__/InformationSummary.test.js
  f2/src/summary/__tests__/MoneyLostSummary.test.js
  f2/src/summary/__tests__/SuspectCluesSummary.test.js
  f2/src/summary/__tests__/WhatHappenedSummary.test.js
  f2/src/summary/__tests__/WhatWasAffectedSummary.test.js
  f2/src/utils/__tests__/formatList.test.js
  f2/src/utils/formatList.js
Labels: need for launch

#1278 Update Azure Script for Log Analytics
  utils/azurescript.sh
  utils/logs.json
  utils/logsacr.json
  utils/logscontentmod.json
  utils/logscosmos.json
  utils/metrics.json
  utils/metricsgrained.json
Labels: infrastructure

#1326 Add VNET and SUBNETS
  utils/azurescript.sh
Labels: infrastructure

#1440 Adding DEV, Staging and PROD to pipeline
  f2/azure-pipelines.yaml
Labels: infrastructure

#1494 Use our own ClamAV image
  utils/azurescript.sh
Labels: infrastructure

#1524 Resource tagging
  utils/azurescript.sh
Labels: infrastructure

#1526 Blob Storage and App Variables
  utils/azurescript.sh
Labels: infrastructure

#1537 Fixes for Azure Build Script after test run
  utils/azurescript.sh
Labels: infrastructure

#1545 Update azurescript to fix clamAV
  utils/azurescript.sh
Labels: infrastructure

#1530 Set availability
  f2/.env.example
  f2/package-lock.json
  f2/package.json
  f2/server.js
  f2/src/utils/checkIfAvailable.js
Labels: need for launch

#1586 Remove extra fields info in the analyst report
  f2/src/ConfirmationPage.js
  f2/src/ConfirmationSummary.js
Labels: need for launch

#1589 fixed some glitches in the button colors
  f2/src/CancelPage.js
  f2/src/ThankYouPage.js
  f2/src/components/button/index.js
Labels: need for launch

#1598 Add subject for encrypted analyst report email
  f2/src/utils/encryptedEmail.js
Labels: need for launch

#1584 Uifix cancel page layout
  f2/src/CancelPage.js
Labels: need for launch

#1596 added location to identify which page the feedback came from
  f2/src/forms/MidFeedbackForm.js
  f2/src/forms/__tests__/MidFeedbackForm.test.js
Labels: need for launch

#1567 Buttons flexbug 9
  f2/azure-pipelines.yaml
  f2/src/components/button/index.js
  f2/src/components/next-and-cancel-buttons/_tests_/next-and-cancel-buttons.test.js
  f2/src/forms/__tests__/BusinessInfoForm.test.js
  f2/src/forms/__tests__/ContactInfoForm.test.js
  f2/src/forms/__tests__/DevicesForm.test.js
  f2/src/forms/__tests__/FinalFeedbackForm.test.js
  f2/src/forms/__tests__/HowDidItStartForm.test.js
  f2/src/forms/__tests__/InformationForm.test.js
  f2/src/forms/__tests__/LocationInfoForm.test.js
  f2/src/forms/__tests__/MidFeedbackForm.test.js
  f2/src/forms/__tests__/MoneyLostInfoForm.test.js
  f2/src/forms/__tests__/PrivacyConsentInfoForm.test.js
  f2/src/forms/__tests__/WhatHappenedForm.test.js
  f2/src/forms/__tests__/WhatWasAffectedForm.test.js
Labels: need for launch

#1593 Hookup finalfeedback thanks page
  f2/src/ConfirmationPage.js
  f2/src/FinalFeedbackPage.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
Labels: need for launch

#1601 Flag cm in subject
  f2/src/utils/encryptedEmail.js
Labels: need for launch

#1604 Update prod release candidate
  f2/.env.example
  f2/Dockerfile
  f2/azure-pipelines.yaml
  f2/package-lock.json
  f2/package.json
  f2/server.js
  f2/src/CancelPage.js
  f2/src/ConfirmationPage.js
  f2/src/ConfirmationSummary.js
  f2/src/FinalFeedbackPage.js
  f2/src/PrivacyStatementPage.js
  f2/src/ThankYouPage.js
  f2/src/components/button/index.js
  f2/src/components/header/presets.js
  f2/src/components/next-and-cancel-buttons/_tests_/next-and-cancel-buttons.test.js
  f2/src/forms/InformationForm.js
  f2/src/forms/MidFeedbackForm.js
  f2/src/forms/__tests__/BusinessInfoForm.test.js
  f2/src/forms/__tests__/ContactInfoForm.test.js
  f2/src/forms/__tests__/DevicesForm.test.js
  f2/src/forms/__tests__/FinalFeedbackForm.test.js
  f2/src/forms/__tests__/HowDidItStartForm.test.js
  f2/src/forms/__tests__/InformationForm.test.js
  f2/src/forms/__tests__/LocationInfoForm.test.js
  f2/src/forms/__tests__/MidFeedbackForm.test.js
  f2/src/forms/__tests__/MoneyLostInfoForm.test.js
  f2/src/forms/__tests__/PrivacyConsentInfoForm.test.js
  f2/src/forms/__tests__/WhatHappenedForm.test.js
  f2/src/forms/__tests__/WhatWasAffectedForm.test.js
  f2/src/locales/en.json
  f2/src/locales/fr.json
  f2/src/utils/checkIfAvailable.js
  f2/src/utils/encryptedEmail.js
  f2/src/utils/formatAnalystEmail.js
  f2/src/utils/getData.js
Labels: need for launch
